# This file is not in use in this package.
# Instead, I am using alpine/ansible https://hub.docker.com/r/alpine/ansible via the docker-compose

# vi Dockerfile

# Dockerfile Content

FROM ubuntu:20.04
ENV ANSIBLE_VERSION 2.12.3
RUN apt-get update; \
    apt-get install -y gcc python3; \
    apt-get install -y python3-pip; \
    apt-get clean all
RUN pip3 install --upgrade pip; \
    pip3 install "ansible==${ANSIBLE_VERSION}";