# roles/apt/handlers/main.yml

- name: Update apt cache
  apt:
    update_cache: yes

- name: Perform dist-upgrade
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
  register: update_result
  notify: Reboot the server
  