# Ansible Requirements File

# Benefits of Using requirements.yml
# Version Control: You can keep requirements.yml under version control, tracking changes to your dependencies just as you do with your playbook code.

# 1. Consistency: Ensures that everyone working on the project, or any automation systems you use, 
#    are utilizing the same versions of collections and roles, leading to more predictable outcomes.

# 2. Simplification: Cleans up your playbook by removing manual installation tasks, 
#    focusing on the state you want to achieve rather than the setup process.

collections:
  - name: community.general
    # Specify a version number or 'latest' for the latest version
    # This should ultimately change to a specific version for stability moving forward
    # Ensure that this is updated once testing is done and the environment is stable
    version: 'latest'
